### PR TITLE
refactor code to use click and setuptools, update readme, create gitgnore, mode reference genome to data

### PR DESCRIPTION
**Pull request by dezordi**
## Solve the following bugs:

- requirements not listed:
    psutil
    scipy
- broken imports:
    - detect_sample.py
        - imports should be imported from sub-modules
            from pyiSNV.building_ref_db import GenomeMapBuilder 
            from pyiSNV.building_reads_db import SampleMapBuilder 
            from pyiSNV.building_connection_table import ConnectMapBuilder 
            from pyiSNV.output_iSNV_area import VariantLocator
            from pyiSNV.recognise_isnv import VariantCaller 

## Refactor code to use click and setuptools
- detect_sample.py and detect_multi_samples are transformed on click commands
- the functions present on detect_sample and detect_multi_samples were moved to `pyisnv`  module
- the reference genome was moved to a specific dir named `data` to separate from tool code
- click stylized messages are used to deal with error execution
- the example codes are updated to receive arguments with sys.argv to avoid that the user should edit the codes
- the documentation was updated accordingly

### CODE REVIEW

**Comment by dezordi** [comment]
Dear @bnuLyndon 

Recently, I had the pleasure of reading the article titled "PySNV for complex intra-host variation detection" and I was truly impressed by the PySNV tool discussed within it. Excited to delve deeper, I attempted to test the tool myself, only to encounter some errors related to the code structure. Given my background in bioinformatics development, I took the liberty of making some adjustments to the code, transforming it into a Python tool and package that can be executed via command line or imported into other scripts.

I have this a pull request and I noticed that the main branch lacks any rule of protection. Considering the importance of maintaining code integrity, I recommend implementing a protection rule wherein pull requests to the main branch require review and approval from one or two designated reviewers.

I believe these enhancements will further elevate the utility and reliability of the PySNV tool. I look forward to any feedback you may have on my contributions, and I am eager to collaborate further on improving this valuable resource for the bioinformatics community.

I put the PR as draft to avoid the approval without your review, once the repository as no protection rule.

Feel free to contact-me via e-mail: `filipe.zimmer@fiocruz.br`

Thank you for your time and consideration.

**Comment by lyndonstatigen** [comment]
Hi Dezordi, thanks for the commits. These are good advice, I will look at them. Basically I need to make sure the previous command is working as well, which was listed in the paper.

**Comment by bnuLyndon** [comment]
Hi Dezordi, thanks for the commits. They are good advice and I will look at them. Basically I need to make sure the previous command is working as well, which was listed in the paper.

**Comment by dezordi** [comment]
> Hi Dezordi, thanks for the commits. They are good advice and I will look at them. Basically I need to make sure the previous command is working as well, which was listed in the paper.

Hi Liandong, Ok! When you report that everything is ok, I will remove the draft status from PR so that it can be merged. If I can help with anything else, just let me know.

**Review by bnuLyndon — APPROVED** [review]

**Pull request merged**
